spring.application.name=NovaBuild


spring.datasource.url=jdbc:postgresql://ep-super-hall-az44oqj5-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${jwt_secret}

stripe.secret=${STRIPE_API_KEY}
stripe.webhook.secret=${Stripe_Webhook_Secret}

client.url=http://localhost:8080/