apiVersion: v1
kind: ConfigMap
metadata:
  name: novabuild-configmap
  namespace: novabuild
data:
  EUREKA_URI: "http://discovery-service:8761/eureka/"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATASOURCE_USERNAME: "postgres"
  JWT_SECRET: "novabuild-lovable-clone-super-secret-key-2026-production-32bytes"
