apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: novabuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgrespassword"
            - name: POSTGRES_MULTIPLE_DATABASES
              value: "novabuild_account_db,novabuild_project_db,novabuild_intelligent_db,novabuild_sandbox_db"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: novabuild
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
